/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Monster (https://sketchfab.com/monster)
license: CC-BY-NC-ND-4.0 (http://creativecommons.org/licenses/by-nc-nd/4.0/)
source: https://sketchfab.com/3d-models/spinosaurus-d98b4f7dcf6d40b8b1f0b5523b3f551a
title: Spinosaurus
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Spinosaurus(props) {
  const { nodes, materials } = useGLTF(
    "models/spinosaurus/spinosaurus-transformed.glb"
  );
  const { scale, position, rotation } = props;
  return (
    <group
      {...props}
      dispose={null}
      scale={scale}
      position={position}
      rotation={rotation}
    >
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.09}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group rotation={[-Math.PI / 2, 0, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.spino_v02_printable_Standardmaterial_0.geometry}
              material={materials.Standardmaterial}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.spino_v02_printable_Standardmaterial_0_1.geometry}
              material={materials.Standardmaterial}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.spino_v02_printable_Standardmaterial_0_2.geometry}
              material={materials.Standardmaterial}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("models/spinosaurus/spinosaurus-transformed.glb");
