/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: DailyArt (https://sketchfab.com/D.art)
license: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
source: https://sketchfab.com/3d-models/stegosaurus-1924052361fb4bd49b714d296a34d2ab
title: Stegosaurus
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function Stegosaurus(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(
    "models/stegosaurus/stegosaurus-transformed.glb"
  );
  const { actions } = useAnimations(animations, group);

  const { scale, position, rotation } = props;
  return (
    <group
      ref={group}
      {...props}
      dispose={null}
      scale={scale}
      position={position}
      rotation={rotation}
    >
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="Stegosaurus_fbxFBX" rotation={[Math.PI / 2, 0, 0]}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Object_4">
                  <primitive object={nodes._rootJoint} />
                  <skinnedMesh
                    name="Object_7"
                    geometry={nodes.Object_7.geometry}
                    material={materials.jianlong}
                    skeleton={nodes.Object_7.skeleton}
                    castShadow
                  />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("models/stegosaurus/stegosaurus-transformed.glb");
