/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: DailyArt (https://sketchfab.com/D.art)
license: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
source: https://sketchfab.com/3d-models/tyrannosaurus-rex-9d3a3e42c0054c35aa39c3ee07388d16
title: Tyrannosaurus Rex
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function Tyrannosaurus(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(
    "models/tyrannosaurus/tyrannosaurus-transformed.glb"
  );
  const { actions } = useAnimations(animations, group);

  const { scale, position, rotation } = props;
  return (
    <group
      ref={group}
      {...props}
      dispose={null}
      scale={scale}
      position={position}
      rotation={rotation}
    >
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group
                name="Bip001_125"
                position={[0, 3.79, -0.08]}
                rotation={[0.11, -Math.PI / 2, 0]}
                scale={0.03}
              >
                <group name="GLTF_created_0">
                  <primitive object={nodes.GLTF_created_0_rootJoint} />
                  <skinnedMesh
                    name="Object_7"
                    geometry={nodes.Object_7.geometry}
                    material={materials.bawanglong}
                    skeleton={nodes.Object_7.skeleton}
                    castShadow
                  />
                  <skinnedMesh
                    name="Object_8"
                    geometry={nodes.Object_8.geometry}
                    material={materials.bawanglong}
                    skeleton={nodes.Object_8.skeleton}
                    castShadow
                  />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("models/tyrannosaurus/tyrannosaurus-transformed.glb");
